# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-06 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0002_auto_20161004_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freetext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_text', models.CharField(max_length=1000)),
            ],
        ),
    ]
