# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-06 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0005_auto_20161006_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.IntegerField(default=0),
        ),
    ]
